### ISSUE TITLE
安装后太卡，直接ANR

### ISSUE THREAD

**Issue by zhijieeeeee** [jixiaoyong/WanAndroid#2]

**Comment by jixiaoyong** [comment]
@zhijieeeeee 你好，方便提供一下手机的android版本、内存大小、网络状况（WiFi/3g/4g）等信息吗？谢谢！

**Comment by zhijieeeeee** [comment]
vivo X6A ,Android 5.0.2，4G运行内存，wifi

**Comment by GodFan4** [comment]
刚进入主页的时候，滑动列表确实卡，大约等个20s之后就好了，三星 s9+，android 8.0  6G内存，wifi

**Comment by wanjuanjuanv** [comment]
主页跑马灯很卡，pixel2  8.1.0 4GB内存

**Comment by jixiaoyong** [comment]
谢谢大家的关注，之前都是用的虚拟机，最近拿到一台4G的实体机，测了一下目前WiFi环境下，卡顿主要在下滑列表时，还有就是页面横滑切换两个地方。

 * 下滑列表卡顿主要是会在后台加载数据，这里判断的逻辑有点问题，有时间会尽快修复。
*  横滑切换的问题还在定位中。
*  主页跑马灯似乎有内存泄漏问题，后期会修复。
*  另外，之前在README中的apk连接较源码滞后一些，我在最近更新了该apk，如果有兴趣欢迎尝试（[点击下载](https://raw.githubusercontent.com/jixiaoyong/Notes-Files/master/download/apk/WanAndroid.apk)）。

 再次谢谢大家！

@zhijieeeeee @GodFan4 @wanjuanjuanv

**Comment by jixiaoyong** [comment]
最新版本已经解决卡顿问题
